eHotelServices/Aplikacija/EHotelServices/EHotelServices/Models/Administrator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace EHotelServices.Models
{
    public class Administrator
    {
        [Key, ConcurrencyCheck, MaxLength(20),MinLength(5)]
        public String Username { get; set; }
        [ConcurrencyCheck, MaxLength(20),MinLength(5),Required]
        public String Password { get; set; }
        
        public String Ime { get; set;}
        public String Prezime { get; set; }
        public String PibHotela { get; set; }

    }
}

eHotelServices/Aplikacija/EHotelServices/EHotelServices/Controllers/AdministratorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EHotelServices.Models;

namespace EHotelServices.Controllers
{
    public class AdministratorsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Administrators
        public ActionResult Index()
        {
            return View(db.Admin.ToList());
        }

        // GET: Administrators/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Administrator administrator = db.Admin.Find(id);
            if (administrator == null)
            {
                return HttpNotFound();
            }
            return View(administrator);
        }

        // GET: Administrators/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Administrators/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Username,Password,Ime,Prezime,PibHotela")] Administrator administrator)
        {
            if (ModelState.IsValid)
            {
                db.Admin.Add(administrator);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(administrator);
        }

        // GET: Administrators/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Administrator administrator = db.Admin.Find(id);
            if (administrator == null)
            {
                return HttpNotFound();
            }
            return View(administrator);
        }

        // POST: Administrators/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Username,Password,Ime,Prezime,PibHotela")] Administrator administrator)
        {
            if (ModelState.IsValid)
            {
                db.Entry(administrator).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(administrator);
        }

        // GET: Administrators/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Administrator administrator = db.Admin.Find(id);
            if (administrator == null)
            {
                return HttpNotFound();
            }
            return View(administrator);
        }

        // POST: Administrators/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Administrator administrator = db.Admin.Find(id);
            db.Admin.Remove(administrator);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

eHotelServices/Aplikacija/EHotelServices/EHotelServices/Controllers/HotelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EHotelServices.Models;
using Microsoft.AspNet.Identity;

namespace EHotelServices.Controllers
{
    public class HotelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Hotels
        public ActionResult Index()
        {
            return View(db.Hoteli.ToList());
        }

        [HttpGet]
        public ActionResult ViewZaGosta()
        {
            return View(db.Hoteli.ToList());
        }

        // GET: Hotels/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hoteli.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // GET: Hotels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Hotels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PibHotela,Ime,Lokacija,Opis,Slika")] Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                db.Hoteli.Add(hotel);
                db.SaveChanges();
                return RedirectToAction("AddHotelImage", "Image", new { pib = hotel.PibHotela });
            }

            return View(hotel);
        }

        // GET: Hotels/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hoteli.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // POST: Hotels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PibHotela,Ime,Lokacija,Opis,Slika")] Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hotel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("EditHotelImage", "Image", new { pib = hotel.PibHotela });
            }
            return View(hotel);
        }

        // GET: Hotels/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hoteli.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // POST: Hotels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Hotel hotel = db.Hoteli.Find(id);
            db.Hoteli.Remove(hotel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UslugeZaGosta(string pib)
        {
            return RedirectToAction("IndexZaGosta", "Uslugas", new { id = pib });
        }

        public ActionResult Profil()
        {
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
            int idG = db.Gosti.Where(x => x.eMail == currentUser.Email).FirstOrDefault().GostId;

            return RedirectToAction("Details", "Gosts", new { id = idG});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

eHotelServices/Aplikacija/EHotelServices/EHotelServices/Controllers/OsobljesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EHotelServices.Models;

namespace EHotelServices.Controllers
{
    public class OsobljesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Osobljes
        public ActionResult Index()
        {
            return View(db.Zaposleni.ToList());
        }

        // GET: Osobljes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Osoblje osoblje = db.Zaposleni.Find(id);
            if (osoblje == null)
            {
                return HttpNotFound();
            }
            return View(osoblje);
        }

        // GET: Osobljes/Create
        public ActionResult Create(string email)
        {
            string username = (string)email.Split('@')[0];
            var osoblje = new Osoblje() { Username = username, Email = email };
            return View(osoblje);
        }

        // POST: Osobljes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OsobljeId,Username,Ime,Prezime,DatumRodjenja,BrRacuna,OpisDuznosti,PibHotela,Email,Odobren")] Osoblje osoblje)
        {
            if (ModelState.IsValid)
            {
                osoblje.Odobren = false;
                db.Zaposleni.Add(osoblje);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(osoblje);
        }

        // GET: Osobljes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Osoblje osoblje = db.Zaposleni.Find(id);
            if (osoblje == null)
            {
                return HttpNotFound();
            }
            return View(osoblje);
        }

        // POST: Osobljes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OsobljeId,Username,Ime,Prezime,DatumRodjenja,BrRacuna,OpisDuznosti,PibHotela,Email,Odobren")] Osoblje osoblje)
        {
            if (ModelState.IsValid)
            {
                db.Entry(osoblje).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(osoblje);
        }

        // GET: Osobljes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Osoblje osoblje = db.Zaposleni.Find(id);
            if (osoblje == null)
            {
                return HttpNotFound();
            }
            return View(osoblje);
        }

        // POST: Osobljes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Osoblje osoblje = db.Zaposleni.Find(id);
            db.Zaposleni.Remove(osoblje);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult AzurirajPIB(int id, string pib)
        {
            using (ApplicationDbContext dbc = new ApplicationDbContext())
            {

                Osoblje o = dbc.Zaposleni.Where(x => x.OsobljeId == id).FirstOrDefault();
                if (o != null)
                {
                    o.PibHotela = pib;
                    dbc.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }

        public ActionResult Odobri(string username)
        {
            using (ApplicationDbContext dbc = new ApplicationDbContext())
            {

                Osoblje o = dbc.Zaposleni.Where(x => x.Username == username).FirstOrDefault();
                if (o != null)
                {
                    o.Odobren = true;
                    dbc.SaveChanges();
                }
                return RedirectToAction("Index");
            }
        }


    }
}

eHotelServices/Aplikacija/EHotelServices/EHotelServices/Views/Administrators/Create.cshtml
@model EHotelServices.Models.Administrator

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Administrator</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PibHotela, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PibHotela, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PibHotela, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eHotelServices/Aplikacija/EHotelServices/EHotelServices/Views/Administrators/Delete.cshtml
@model EHotelServices.Models.Administrator

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Administrator</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PibHotela)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PibHotela)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

eHotelServices/Aplikacija/EHotelServices/EHotelServices/Views/Administrators/Details.cshtml
@model EHotelServices.Models.Administrator

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Administrator</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prezime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PibHotela)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PibHotela)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Username }) |
    @Html.ActionLink("Back to List", "Index")
</p>

eHotelServices/Aplikacija/EHotelServices/EHotelServices/Views/Administrators/Edit.cshtml
@model EHotelServices.Models.Administrator

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Administrator</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Username)

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prezime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prezime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PibHotela, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PibHotela, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PibHotela, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eHotelServices/Aplikacija/EHotelServices/EHotelServices/Views/Administrators/Index.cshtml
@model IEnumerable<EHotelServices.Models.Administrator>

@{
    ViewBag.Title = "Index";
}
 <h1>
     Admin Panel
 </h1>
<hr />
<div>
    <div>
        <h2>

            @Html.ActionLink("Lista gostiju", "Index", "Gosts")
        </h2>

    </div>
    <hr />
    <div>
        <h2>
            @Html.ActionLink("Lista zaposlenih", "Index", "Osobljes")


        </h2>
    </div>
    <hr />
    <div>
        <h2>
            @Html.ActionLink("Lista hotela", "Index", "Hotels")

        </h2>
    </div>
    <hr />
    <div>
        <h2>
            @Html.ActionLink("Kreiraj hotel", "Create", "Hotels")

        </h2>
    </div>

</div>